### ISSUE TITLE
Inline PowerShell step not reflecting nonzero exit codes.

### ISSUE THREAD

**Issue by JacobHenner** [XpiritBV/Vsts-Build-Task-InlinePowershell#8]
When running an inline PowerShell script using this module, nonzero exit codes are not causing the release job to show a failure, when they should be. _Continue on error_ is not selected. 

The bundled PowerShell task running the same script in inline mode reflects the failure properly.

**Comment by JacobHenner** [comment]
Simple test:
```
Write-Host "Hello, world"
exit 1
```

**Comment by pgroene** [comment]
Thx for the report, I think you can work around it with   "##vso[task.complete result=Failed]" instead of exit 1. I'll have a look on how to support exit codes

**Comment by pgroene** [comment]
After some research I could look at the last exit code. However most of the script will not have a last exit code and than it just takes the value from the last time an exit code has set. That will lead to a lot of random errors for scripts without exit codes. So that is not really a fix. 
the best way to stop error the task is to print:

"##vso[task.complete result=Failed]"

If you have a better solution that works with and with exit codes. Please let me know.

**Comment by JacobHenner** [comment]
@pgroene Thank you for looking into this. I'm not aware of a better solution, I'll use the ##vso step instead.
